<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'title' => 'Harika Kahve',
                'category_id' => 2,
                'category_title' => 'Kahve',
                'description' => 'Özel karışım, harika lezzet!',
                'price' => 24.99,
                'stock_quantity' => 50,
                'origin' => 'Brezilya',
                'roast_level' => 'Orta',
                'flavor_notes' => json_encode(['Çikolata', 'Fındık', 'Vanilya']),
                'is_active' => 1,
            ],
            [
                'id' => 2,
                'title' => 'Yoğun Lezzet',
                'category_id' => 2,
                'category_title' => 'Kahve',
                'description' => 'Güçlü ve yoğun aromalar.',
                'price' => 29.99,
                'stock_quantity' => 30,
                'origin' => 'Kolombiya',
                'roast_level' => 'Koyu',
                'flavor_notes' => json_encode(['Karamel', 'Kara Kiraz', 'Baharatlı']),
                'is_active' => 1,
            ],
            [
                'id' => 3,
                'title' => 'Hafif Sipariş',
                'category_id' => 2,
                'category_title' => 'Kahve',
                'description' => 'Hafif ve ferahlatıcı bir deneyim.',
                'price' => 19.99,
                'stock_quantity' => 40,
                'origin' => 'Etiyopya',
                'roast_level' => 'Hafif',
                'flavor_notes' => json_encode(['Meyve', 'Çiçek', 'Nane']),
                'is_active' => 1,
            ],
            [
                'id' => 4,
                'title' => 'Espresso Gücü',
                'category_id' => 2,
                'category_title' => 'Kahve',
                'description' => 'Espresso severler için güçlü bir tercih.',
                'price' => 27.99,
                'stock_quantity' => 25,
                'origin' => 'İtalya',
                'roast_level' => 'Orta-Koyu',
                'flavor_notes' => json_encode(['Çikolata', 'Fındık', 'Kavrulmuş Ekmek']),
                'is_active' => 1,
            ],
            [
                'id' => 5,
                'title' => 'Özel Karışım',
                'category_id' => 2,
                'category_title' => 'Kahve',
                'description' => 'Uzmanlar tarafından özel olarak hazırlanan karışım.',
                'price' => 34.99,
                'stock_quantity' => 20,
                'origin' => 'Karışık',
                'roast_level' => 'Orta',
                'flavor_notes' => json_encode(['Karışık Notlar']),
                'is_active' => 1,
            ],
            [
                'id' => 6,
                'title' => 'Doğal Yollarla Yetiştirilmiş',
                'category_id' => 2,
                'category_title' => 'Kahve',
                'description' => 'Kimyasal gübre veya ilaç içermez.',
                'price' => 39.99,
                'stock_quantity' => 15,
                'origin' => 'Peru',
                'roast_level' => 'Hafif',
                'flavor_notes' => json_encode(['Meyve', 'Çiçek', 'Ahududu']),
                'is_active' => 1,
            ],
            [
                'id' => 7,
                'title' => 'Geleneksel Türk Kahvesi',
                'category_id' => 2,
                'category_title' => 'Kahve',
                'description' => 'Türk kahvesi keyfi evinizde!',
                'price' => 22.99,
                'stock_quantity' => 35,
                'origin' => 'Türkiye',
                'roast_level' => 'Orta',
                'flavor_notes' => json_encode([]),
                'is_active' => 1,
            ],
            [
                'id' => 8,
                'title' => 'Vanilla Dream',
                'category_id' => 2,
                'category_title' => 'Kahve',
                'description' => 'Vanilya sevenler için rüya gibi bir kahve.',
                'price' => 31.99,
                'stock_quantity' => 28,
                'origin' => 'Madagaskar',
                'roast_level' => 'Orta',
                'flavor_notes' => json_encode(['Vanilya', 'Karamel', 'Hafif Baharatlı']),
                'is_active' => 1,
            ],
            [
                'id' => 9,
                'title' => 'Tropikal Rüya',
                'category_id' => 2,
                'category_title' => 'Kahve',
                'description' => 'Tropikal meyve notalarıyla dolu bir rüya.',
                'price' => 37.99,
                'stock_quantity' => 17,
                'origin' => 'Kosta Rika',
                'roast_level' => 'Orta',
                'flavor_notes' => json_encode(['Mango', 'Ananas', 'Kokos']),
                'is_active' => 1,
            ],
        ]);
    }
}
